### PR TITLE
[RHCLOUD-19369] Fix rhc connection tests

### PR DESCRIPTION
**Pull request by petracihalova**
In https://github.com/RedHatInsights/sources-api-go/pull/124 were some tests commented and here is fix for this.

The only change is uncommenting commented tests

**JIRA:** [RHCLOUD-19369](https://issues.redhat.com/browse/RHCLOUD-19369)

------------
edit:
the issue is not present on dev db so uncommented tests should pass after #203 merge

### CODE REVIEW

**Review by MikelAlejoBR — APPROVED** [review]
LGTM. Were the tests failing because the join table had orphaned rows?

**Comment by petracihalova** [comment]
> LGTM. Were the tests failing because the join table had orphaned rows?

the reason was that when we changed in https://github.com/RedHatInsights/sources-api-go/pull/124 the struct `SourceRhcConnection`, the Gorm was creating some foreign keys and that caused this err

`ERROR: update or delete on table "rhc_connections" violates foreign key constraint "fk_delete_source_rhc_connections_rhc_connection" on table "source_rhc_connections" (SQLSTATE 23503)`

**Comment by MikelAlejoBR** [comment]
Aaaah I see. Thanks for the explanation!

**Comment by petracihalova** [comment]
after discussion with @lpichler (👍🏻  thanks Libor) I converted this PR to draft because this troubles with rhc-connection tests seems to not exist on development db, so probably it will be fixed by https://github.com/RedHatInsights/sources-api-go/pull/203 ... so I will take this as draft and after merging PR203 we can reuse at lest the uncommenting of tests

**Comment by petracihalova** [comment]
waiting for #203 merge

**Comment by petracihalova** [comment]
summary:
- original idea was to add db constraint for allowing the cascade delete (that's why the branch name is what it is)
- then I realised that this issue is not present in dev db, so merge of #203 should have solved it (and it did)
- now this PR contains only the uncommenting of commented tests (that are now passing)

this PR is rebased & ready for review

**Review by lindgrenj6 — APPROVED** [review]
:tada:

**Pull request merged**
