### PR TITLE
[RHCLOUD-20415] Mock daos refactor

### PR DESCRIPTION
**Pull request by petracihalova**
for all mock daos:

- unified receivers names 
- changed unused param into underscore

**JIRA:** [RHCLOUD-20415](https://issues.redhat.com/browse/RHCLOUD-20415)

### CODE REVIEW

**Comment by petracihalova** [comment]
this PR will be rebased after #547 merge

**Comment by petracihalova** [comment]
rebased and ready for review

**Comment by petracihalova** [comment]
tests failed because of changes from #550 (tests needs to be updated)

**Review by MikelAlejoBR — APPROVED** [review]
LGTM!

**Review by Ellen-Yi-Dong — APPROVED** [review]
LGTM!

**Review by lindgrenj6 — APPROVED** [review]

**Review by lpichler — APPROVED** [review]

**Pull request merged**
