### PR TITLE
Reorganize various Authentication DAOs

### PR DESCRIPTION
**Pull request by lindgrenj6**
Based on #607, so that one will need to go first. 

This PR does a few things:
1. Renames `authenticationDaoImpl` -> `authenticationDaoVaultImpl` since that is what it is
2. Moves `VaultClient` itnerface (and creation) to `dao/vault` since it is a separate package
3. Creates `dao/amazon` for the secrets manager client
4. Initial empty secrets manager authentication dao impl

### CODE REVIEW

**Comment by lpichler** [comment]
@lindgrenj6 this can be rebased

**Review by lpichler — APPROVED** [review]

**Comment by lindgrenj6** [comment]
rebased!

**Comment by lindgrenj6** [comment]
/retest

EDIT: bonfire error.

**Comment by lindgrenj6** [comment]
Merging due to approval.

**Pull request merged**
