### PR TITLE
Use cji_smoke_test instead of smoke_test.sh in pr_check.sh

### PR DESCRIPTION
**Pull request by lpichler**

### CODE REVIEW

**Review by MikelAlejoBR — APPROVED** [review]

**Comment by lindgrenj6** [comment]
It looks like the cji smoketest script is looking for the wrong clowdapp, it's looking for `sources-api-go` instead of `sources-api`:
```
08:49:39 2022-07-11 13:49:39 [   ERROR] [          MainThread] [clowdjobinvocation/sources-api-go] not ready, details: clowdjobinvocation/sources-api-go not ready, status conditions:
08:49:39   - JobInvocationComplete: False (Some Jobs are still incomplete)
08:49:39   - ReconciliationFailed: True (ClowdApp.cloud.redhat.com "sources-api-go" not found)
08:49:39   - ReconciliationSuccessful: False
08:49:39 
08:49:39 ERROR: deploy-iqe-cji: hit timeout error: Could not do 'wait for Job to appear owned by CJI 'sources-api-go'' at /srv/volume/jenkins/workspace/RedHatInsights-sources-api-go-pr-check/.bonfire_venv/lib64/python3.6/site-packages/bonfire/openshift.py:204 in time
```

**Comment by lindgrenj6** [comment]
So it really looks like a lot more tests ran - but a lot of them failed particularly the bulk_create then wait for available ones, which makes sense because we aren't running cloud-meter or cost to tell us the availability status. 

I want to merge this - but can't unless we can get it to go green. It's "unstable" right now which still results in red tests.

**Comment by lindgrenj6** [comment]
I'm actually going to merge this. That way even though the tests will be red the unit/integration tests will still get ran.

**Pull request merged**
