### PR TITLE
Add missing marketplace logo

### PR DESCRIPTION
**Pull request by epwinchell**
Jira: https://issues.redhat.com/browse/RHCLOUD-20370
Follow-up to: https://github.com/RedHatInsights/frontend-assets/pull/58

Screen Shot 2022-07-27 at 9 25 50 AM

### CODE REVIEW

**Comment by epwinchell** [comment]
@MikelAlejoBR @lindgrenj6  Could someone make sure that I grabbed the correct version of the logo for this? Thanks. 

(We might also want to do the same for OpenShift)

**Comment by MikelAlejoBR** [comment]
Hey @epwinchell,

It looks good to me. I've copied & pasted the image's `src` on the stage UI for sources and this is how it looks:

red_hat_source
 
However I don't know if this is how it should look... maybe we need to talk to UX to validate it? :eyes:

**Comment by epwinchell** [comment]
@MikelAlejoBR Thanks. Could you loop in the Sources UX person? I'm thinking we ditch the Marketplace text below and do something similar for OpenShift or we just use the Red Hat logo for both.

**Comment by MikelAlejoBR** [comment]
Hey @epwinchell,

So I talked to UX and they told me to just leave it as the "OpenShift Container Platform": just the Red Hat above and the "Marketplace" text below, and we should be good.

**Comment by epwinchell** [comment]
@MikelAlejoBR Thank you. PR updated.

**Review by MikelAlejoBR — APPROVED** [review]
Looking good! Thank you very much!

**Review by lindgrenj6 — APPROVED** [review]

**Review by lpichler — APPROVED** [review]

**Pull request merged**
