### PR TITLE
[RHCLOUD-19271] feature: remove the "Catalog" application from sources

### PR DESCRIPTION
**Pull request by MikelAlejoBR**
It seems like this application will no longer be used, so we've been asked to remove it. The related "ansible-tower" source can be removed as well, since there are no other applications compatible with that source.

## Links

[[RHCLOUD-19271]](https://issues.redhat.com/browse/RHCLOUD-19271)

### CODE REVIEW

**Review by lpichler — APPROVED** [review]

**Review by lindgrenj6 — APPROVED** [review]

**Comment by lindgrenj6** [comment]
One question - when we delete this all of the sources + applications will be destroyed out of the DB. Are we ok with that happening on prod? I assume yes. cc @rvsia

**Comment by MikelAlejoBR** [comment]
> One question - when we delete this all of the sources + applications will be destroyed out of the DB. Are we ok with that happening on prod? I assume yes. cc @rvsia

I don't know if the question is for me, but I assumed it was okay. Either that or I misinterpreted the ticket...

**Review by petracihalova — APPROVED** [review]

**Comment by MikelAlejoBR** [comment]
Hey all,

I've confirmed that it is safe to remove catalog from our codebase. So it is safe to merge this.

**Review by lindgrenj6 — APPROVED** [review]
:wave:

**Pull request merged**
