### PR TITLE
Change BulkCreate ApplicationAuthentication logic to work with DB-backed DAO

### PR DESCRIPTION
**Pull request by lindgrenj6**
BulkCreate wasn't working for applicationAuthentications before mostly because of our DB schema being not-correct for the vault backend. 

In the future we're going to need to relax the constraints and change that table's layout a bit to fit both options. But today is not that day since we do not have a vault.

### CODE REVIEW

**Review by lpichler — APPROVED** [review]

**Review by MikelAlejoBR — APPROVED** [review]

**Review by MikelAlejoBR — CHANGES_REQUESTED** [review]
Hang on a minute. I was curious about the following change:

```diff
- VaultPath string `json:"vault_path"`
+ VaultPath string `json:"vault_path" gorm:"-"`
```

Since I remember I had to add it back because some tests are failing. And even though the CI says everything is right... If I issue the `go test ./... -integration` command locally, I get a test failure in the DAO package....

```
--- FAIL: TestDeleteApplicationAuthentication (0.19s)                                                                                                                                                                                       
    application_authentication_dao_test.go:51: incorrect applicationAuthentication deleted. Want "complex uuid" in the authenticationUid field, got ""
```

And a panic from a dereference error in the status listener package. Can you please run the tests locally too with the above command and confirm that it's not just me?

In the meantime I'm going to investigate what's failing.

**Comment by MikelAlejoBR** [comment]
> Since I remember I had to add it back because some tests are failing. And even though the CI says everything is right... If I issue the `go test ./... -integration` command locally, I get a test failure in the DAO package....
> 
> ```
> --- FAIL: TestDeleteApplicationAuthentication (0.19s)                                                                                                                                                                                       
>     application_authentication_dao_test.go:51: incorrect applicationAuthentication deleted. Want "complex uuid" in the authenticationUid field, got ""
> ```

Regarding this error, it corresponds to the following code block:

https://github.com/RedHatInsights/sources-api-go/blob/e70a41501ac415d28047f0dca80b59130fc05be4/dao/application_authentication_dao_test.go#L46-L53

It seems that when I wrote the test, I was using the UUID as an extra check to see if I was fetching the correct application authentication. I guess we can safely delete that code block.

**Comment by MikelAlejoBR** [comment]
> And a panic from a dereference error in the status listener package. Can you please run the tests locally too with the above command and confirm that it's not just me?

Regarding this one, I've been reverting the main branch locally until the tests stopped failing, and it seems that the bug was introduced in the commit https://github.com/RedHatInsights/sources-api-go/commit/bfa08160a1eb3bd6121d75b1dadfec84f4356f3a, after merging the PR https://github.com/RedHatInsights/sources-api-go/pull/168 .

I've opened a ticket so that we don't forget to change the CI command so that it includes all the tests: https://issues.redhat.com/browse/RHCLOUD-18699

---

Since it's unrelated to this PR I think it is safe merging this PR after the DAO test change.

**Comment by lindgrenj6** [comment]
I went through and removed all refs to `AuthenticationUID` and `VaultPath` since those aren't actually in the DB. We can re-add them in if/when we get a Vault.

**Review by MikelAlejoBR — APPROVED** [review]

**Review by lpichler — APPROVED** [review]

**Pull request merged**
