### PR TITLE
Add missing oracle logo

### PR DESCRIPTION
**Pull request by epwinchell**
Jira: https://issues.redhat.com/browse/RHCLOUD-20369
Follow-up to: https://github.com/RedHatInsights/frontend-assets/pull/57

### CODE REVIEW

**Review by MikelAlejoBR — APPROVED** [review]
Hey @epwinchell,

Thanks for opening the PR! I've checked on stage and the icon exists, so I would say this is ready to be merged! Though I see that you had set this PR as a "Draft". Do we need to wait for something else?

Thank you!

**Comment by epwinchell** [comment]
@MikelAlejoBR I haven't been able to test in the UI. If you're able to, I'd appreciate it! Thanks.
(I have another coming for RHT Marketplace)

**Review by lindgrenj6 — APPROVED** [review]

**Comment by lpichler** [comment]
Screenshot 2022-07-29 at 13 12 44

Hey @epwinchell This is screenshot from stage, should not Oracle logo be bigger ?

**Comment by epwinchell** [comment]
@lpichler It's the wrong image for this screen. Follow-up PR https://github.com/RedHatInsights/sources-api-go/pull/472 (needs to be tested before merging)

**Pull request merged**
