### PR TITLE
[RHCLOUD-21109] refactor: string 'x-rh-sources-psk' in event_stream_test.go replaced by existing constant

### PR DESCRIPTION
**Pull request by petracihalova**
after discussion in #562 I decided to create PR for each constant from middleware/headers/headers.go 
- to have smaller PRs and 
- to not have chaos in repo commit history

this PR contains changes related with first constant PSK which is not needed to rename so I only found all places where we use string "x-rh-sources-psk" and I used there this constant

all PRs related with this constant refactor will be registered in https://github.com/RedHatInsights/sources-api-go/issues/570

**JIRA:** [RHCLOUD-21109](https://issues.redhat.com/browse/RHCLOUD-21109)

### CODE REVIEW

**Review by MikelAlejoBR — APPROVED** [review]

**Review by lpichler — APPROVED** [review]

**Comment by petracihalova** [comment]
rebased & conflict solved

**Review by Ellen-Yi-Dong — APPROVED** [review]

**Pull request merged**
