### PR TITLE
Add RHC Connection Availability Check

### PR DESCRIPTION
**Pull request by lindgrenj6**
This is going to sit for a while until #111 is merged, the org_id <-> acct # service is deployed, and getting time to finish it.

Pretty simple process though - loop through all of the join records and request availability from RHC for each of them. It gets returned from the POST request right in the HTTP response, nice!

### CODE REVIEW

**Comment by lindgrenj6** [comment]
Well - it looks like a bunch of RHC Connection DAO tests are failing now that I added the relationships on the struct(s). It may be due to letting gorm generate the relations I'm wondering.

**Comment by lindgrenj6** [comment]
So it turns out we need this functionality yesterday - I commented out all of the failing tests just because they're valid, but adding the GORM relations on the structs just broke most of these. GORM is creating foreign keys etc that make the tests fail. 

For now I would just like to get the RHC availability chekcing code on stage to the satellite folks can validate it.

**Comment by lindgrenj6** [comment]
It looks like an IQE failure, `AttributeError: 'IQEVaultReference' object has no attribute 'openapi_types'`, so probably safe to ignore.

**Review by MikelAlejoBR — APPROVED** [review]

**Review by lpichler — APPROVED** [review]

**Pull request merged**
