### PR TITLE
[RHCLOUD-17839] Delete not used testutils/fixtures.go and small fixes in fixtures package

### PR DESCRIPTION
**Pull request by petracihalova**
https://issues.redhat.com/browse/RHCLOUD-17839

the file testutils/fixtures.go was originally deleted here: https://github.com/RedHatInsights/sources-api-go/pull/56
and was added here: https://github.com/RedHatInsights/sources-api-go/pull/49

but we don't need it

and I fixed layout for parsing time

### CODE REVIEW

**Comment by lindgrenj6** [comment]
I think that test might be flakey. I've had it randomly fail on other PRs as well.

**Comment by lindgrenj6** [comment]
If it doesn't succeed after a few tries though you might need to debug and see
where the test started failing. Maybe the test is depending on data that was in
those fixtures. 

-- 
Jacob Lindgren

Senior Software Engineer - Insights Platform
Red Hat
***@***.***     M: 402-841-6173

**Comment by petracihalova** [comment]
I found out that failing test is connected with my change of layout in time.Parse() and failing test is `sources-api-go/statuslistener/statuslistener_test.go` ... so I move this PR to WIP

**Review by lpichler — APPROVED** [review]

**Comment by lpichler** [comment]
cc @MikelAlejoBR

**Review by MikelAlejoBR — APPROVED** [review]

**Review by lindgrenj6 — APPROVED** [review]

**Pull request merged**
